WIP | 1 | Fibonacci
Lokideos/think_go pull request #1
Opened 2020-10-14 12:30 UTC by Lokideos

2020-10-14 19:00 UTC, DmitriyVTitov requested changes
Какой-то странный алгоритм. Нужно вычислять один конкретный элемент последовательности.
Целый массив для этого ни к чему.

2020-10-14 19:00 UTC, DmitriyVTitov commented on task-1/fibonacci/cmd/calculation/main.go
> +	result := math.Fibonacci(max)
почему `max`? мне нужен один конкретный элемент последовательности.

2020-10-14 19:00 UTC, DmitriyVTitov commented on task-1/fibonacci/pkg/math/math.go
> +}
что-то очень сложное
без теста и проверить-то почти никак

2020-10-14 19:25 UTC, Lokideos commented on task-1/fibonacci/cmd/calculation/main.go
> +	result := math.Fibonacci(max)
Я так понял, что нужно не элемент последовательности вычислять, а максимально большой элемент, меньше заданного числа :) Ну, переделать не сложно - сейчас сделаю.

2020-10-14 19:26 UTC, Lokideos commented on task-1/fibonacci/pkg/math/math.go
> +}
Сейчас передеалю

2020-10-15 21:20 UTC, DmitriyVTitov approved these changes

2020-10-19 12:43 UTC, merged