WIP | 1 | Fibonacci flag, tests
Lokideos/think_go pull request #2
Opened 2020-10-14 15:27 UTC by Lokideos

2020-10-14 19:05 UTC, DmitriyVTitov requested changes
Вы, судя по всему, решали обратную задачу.
Может я неудачно сформулировал.

2020-10-14 19:05 UTC, DmitriyVTitov commented on task-1/fibonacci/pkg/math/math_test.go
> +	want := 13
вы наоборот что ли считаете, номер в последовательности по значению? похоже на то
надо по номеру подсчитать значение числа Фибоначчи. максимальный номер в последовательности - 20.

2020-10-14 19:24 UTC, Lokideos commented on task-1/fibonacci/pkg/math/math_test.go
> +	want := 13
А, я задание не так понял просто. Сейчас переделаю.

2020-10-15 21:19 UTC, DmitriyVTitov approved these changes
OK, работает. Но у вас алгоритм создаёт массив и хранит там все элементы последовательности Фибоначчи вплоть до требуемого. В то время, как для расчёта достаточно двух переменных. Очень неэффективно по памяти. Так что не пропустите лекцию №4 - Алгоритмы!

2020-10-19 12:49 UTC, merged